// Fast lookup table approach
// Lookup module

use crate::core::error::{NpdatetimeError, Result};
use crate::core::date::BS_EPOCH_YEAR;

// Include data generated by build.rs
include!(concat!(env!("OUT_DIR"), "/calendar_data.rs"));

/// Map the generated flat data to the expected format
fn get_bs_month_data() -> Vec<[u8; 12]> {
    let mut result = Vec::new();
    let mut current_year = -1;
    let mut year_data = [0u8; 12];
    
    for &(year, month, days) in BS_CALENDAR_DATA {
        if year != current_year {
            if current_year != -1 {
                result.push(year_data);
            }
            current_year = year;
            year_data = [0u8; 12];
        }
        if month >= 1 && month <= 12 {
            year_data[month as usize - 1] = days;
        }
    }
    result.push(year_data);
    result
}

lazy_static::lazy_static! {
    static ref BS_MONTH_DATA: Vec<[u8; 12]> = get_bs_month_data();
}

/// Returns the number of days in a given BS month using the lookup table
pub fn get_days_in_month(year: i32, month: u8) -> Result<u8> {
    let index = (year - BS_EPOCH_YEAR) as usize;
    if index >= BS_MONTH_DATA.len() {
        return Err(NpdatetimeError::OutOfRange(
            format!("Year {} is out of supported range", year)
        ));
    }

    Ok(BS_MONTH_DATA[index][(month - 1) as usize])
}
